# Generated by Django 5.2 on 2025-05-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
